language: php
php:
  - '7.3'
before_install:
  - phpenv config-rm xdebug.ini
  - pecl install -f pcov
  - composer global require hirak/prestissimo
install:
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover